<a href="https://colab.research.google.com/github/iqraceme/60_Days_of_Udacity/blob/master/Python_Revision_3_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Numpy Revision

Numpy is a linear algebra library for python, the reason it is so important for data science with Python is that almost all of the libraries in the PyData Ecosystem rely on NumPy as one of their main building blocks.

Numpy is also incredibly fast, as it has bindings to C libraries

### Numpy Arrays

In [0]:
my_list1 = [1,2,3]
my_list2 = [1,3,3]

In [0]:
import numpy as np

In [0]:
array =  np.array(my_list1)

In [0]:
array

array([1, 2, 3])

In [0]:
my_mat1 = [[1,2,3],[4,5,6],[7,8,9]]
my_mat2 = [[1,2,3],[4,5,6],[7,8,9]]

In [0]:
np.array(my_mat1)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [0]:
np.arange(1,100)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [0]:
np.arange(0,111,2)

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100, 102,
       104, 106, 108, 110])

In [0]:
np.zeros(3)

array([0., 0., 0.])

In [0]:
np.zeros((3,3))


array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [0]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [0]:
np.linspace(0,10,20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [0]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [0]:
#one dimensional random array
#Unlike linspace we don't need to pass a tuple
np.random.rand(10)

array([0.5650465 , 0.84954983, 0.01620884, 0.78783722, 0.20596901,
       0.88472005, 0.47951292, 0.56135599, 0.26199187, 0.40495479])

In [0]:
#two dimensional random array
np.random.rand(5,5)

array([[0.04079771, 0.3714708 , 0.77664281, 0.70915315, 0.73881066],
       [0.07043396, 0.67260081, 0.62042885, 0.78334909, 0.23553986],
       [0.76855282, 0.61329217, 0.50243188, 0.5121998 , 0.05000739],
       [0.05915585, 0.85624911, 0.95851008, 0.0824149 , 0.72644715],
       [0.82228084, 0.6287468 , 0.86583409, 0.41465478, 0.15512046]])

In [0]:
np.random.randn(5,5)#returns gaussian distribution

array([[-0.25896935, -1.37412839, -0.18027767,  1.35836067, -1.2810635 ],
       [-0.4892735 ,  0.33709094,  0.25336648,  1.10233264, -0.76496363],
       [-1.47217932, -0.06420857, -0.77081397,  0.38984559, -0.43204844],
       [ 1.11024544, -0.57361053, -0.95935694,  0.0329981 , -0.47310308],
       [ 0.01089462,  0.24475916,  0.05916835,  0.4144845 , -0.06867244]])

In [0]:
np.random.randint(1,100) #Returns a random integer from 1-100 not including 100

60

In [0]:
np.random.randint(1,100,10) #Returns 10 random integers from 1-100
#not including 100

array([72,  1, 37, 44, 86, 98, 33, 49, 21, 66])

In [0]:
arr = np.arange(25) #Returns an array from 0-24

In [0]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [0]:
ranarr = np.random.randint(0,50,10)
#Returns  an array of 10 random integers  from 0-50

In [0]:
ranarr

array([48, 36, 16,  4, 38, 28, 32, 29,  7,  0])

In [0]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [0]:
ranarr

array([48, 36, 16,  4, 38, 28, 32, 29,  7,  0])

In [0]:
ranarr.max()


48

In [0]:
ranarr.min()

0

In [0]:
ranarr.argmax()

0

In [0]:
ranarr.argmin()

9

In [0]:
arr.shape

(25,)

In [0]:
arr = arr.reshape(5,5)

In [0]:
arr


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [0]:
arr.dtype

dtype('int64')

In [0]:
from numpy.random import randint

In [0]:
randint(2,10)

5

### Numpy Indexing and Selection

In [0]:
import numpy as np

In [0]:
arr = np.arange(0,11)

In [0]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [0]:
arr[8]

8

In [0]:
arr[7:9]

array([7, 8])

In [0]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [0]:
arr[:8]

array([0, 1, 2, 3, 4, 5, 6, 7])

In [0]:
arr[3:]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [0]:
arr[0:5] = 199 
# Numpy Broadcasting where it can change the value of 0:5 in the array to 100

In [0]:
arr

array([199, 199, 199, 199, 199,   5,   6,   7,   8,   9,  10])

In [0]:
slice_of_arr = arr[0:6]

In [0]:
slice_of_arr[:] = 99

In [0]:
slice_of_arr[:]

array([99, 99, 99, 99, 99, 99])

In [0]:
arr
#Even the original array changes because slic_of_arr is a view of the array
#This is done to avoid memory issues with very large arrays

array([199, 199, 199, 199, 199,   5,   6,   7,   8,   9,  10])

In [0]:
arr_copy = arr.copy() #Now the array is copied

In [0]:
arr_copy[:] = 100
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [0]:
arr

array([199, 199, 199, 199, 199,   5,   6,   7,   8,   9,  10])

In [0]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [0]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [0]:
arr_2d[0]

array([ 5, 10, 15])

In [0]:
arr_2d[0][0]

5

In [0]:
arr_2d[2][1]

40

In [0]:
arr_2d[0],arr_2d[0][0],arr_2d[0][1],arr_2d[0][2]


(array([ 5, 10, 15]), 5, 10, 15)

In [0]:
arr_2d[1],arr_2d[1][0],arr_2d[1][1],arr_2d[1][2]


(array([20, 25, 30]), 20, 25, 30)

In [0]:
arr_2d[2],arr_2d[2][0],arr_2d[2][1],arr_2d[2][2]

(array([35, 40, 45]), 35, 40, 45)

In [0]:
arr_2d[2,0]

35

In [0]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [0]:
arr_2d[1:,0:]

array([[20, 25, 30],
       [35, 40, 45]])

In [0]:
arr = np.arange(1,11)

In [0]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [0]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [0]:
bool_arr = arr > 5

In [0]:
arr[bool_arr] # Returns elements from the array when boolean values are true

array([ 6,  7,  8,  9, 10])

In [0]:
 arr[arr>5] 
    # Method 2 to Returns elements from the array when boolean values are true

array([ 6,  7,  8,  9, 10])

In [0]:
arr[arr<3]

array([1, 2])

In [0]:
arr_2d = np.arange(50).reshape(5,10)

In [0]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [0]:
arr_2d[1:3,3:5]

array([[13, 14],
       [23, 24]])